Block 1 issue 1
mishkalinda123/First pull request #11
Opened 2020-11-19 12:03 UTC by mishkalinda123

2020-11-19 14:09 UTC, Golenzovskiy commented
@mishkalinda123 А что с [этим пулом](https://github.com/mishkalinda123/First/pull/10) было не так так, зачем пересоздан?

2020-11-19 15:41 UTC, Golenzovskiy requested changes
Нужны мелкие правки.

2020-11-19 15:41 UTC, Golenzovskiy commented on block_1/issue_1/style.css
> +    position: absolute;
Старайся избегать абсолютного позиционирования.
Для того, чтобы расположить чекбокс и подпись к нему в одной строке лучше использовать `display: inline-block;` для самой подписи.

2020-11-19 15:41 UTC, Golenzovskiy commented on block_1/issue_1/form.html
> +            <div class="check"><input type="checkbox"></label></div>
Посмотри пример https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
Обычно для расположения чекбокса и подписи в одной строке никаких хитрых приёмов не требуется

2020-11-19 15:41 UTC, Golenzovskiy commented on block_1/issue_1/form.html
> +</form>
"Развалилось" форматирование (отступы). Примени автоформатирование отдельным коммитом.

2020-11-19 15:41 UTC, Golenzovskiy commented on block_1/issue_1/style.css
> +
лишняя строка
не на что не влияет, но и смысла не имеет

2020-11-20 11:49 UTC, mishkalinda123 commented on block_1/issue_1/style.css
> +
убрал

2020-11-22 09:26 UTC, Golenzovskiy requested changes
Файл `block_1/issue_1/form.html` имеет смысл переименовать в `block_1/issue_1/index.html`, т.к. в рамках задачи это единственный файл в этой папке.
См. https://ru.wikipedia.org/wiki/Index.html

В целом все норм, остались косметические правки. Добей их, пожалуйста, и можно брать в работу следующую задачу.

2020-11-22 09:26 UTC, Golenzovskiy commented on block_1/issue_1/form.html
> +                <input type="checkbox" id="subscribeNews" name="subscribe" value="newsletter">
Почему `subscribeNews`? :)
После копирвания примеров из интернета нужно *сразу* адаптировать их под себя. Сейчас это не так важно, но впоследствии это может добавить тебе неожиданных проблем.

2020-11-22 09:26 UTC, Golenzovskiy commented on block_1/issue_1/style.css
> +    position: absolute;
Скорее всего этот стиль теперь лишний? 
От лишних стилей (это касается не только стилей, но и любого "мертвого" кода) нужно избавляться.

2020-11-23 06:15 UTC, mishkalinda123 commented on block_1/issue_1/style.css
> +    position: absolute;
Да я заметил что при удалении absolut ничего не изменилось...
И смысла конечно в нем нету..

2020-11-23 06:22 UTC, mishkalinda123 commented on block_1/issue_1/form.html
> +                <input type="checkbox" id="subscribeNews" name="subscribe" value="newsletter">
Понял! Подправлю!)

2020-11-23 07:22 UTC, Golenzovskiy commented on block_1/issue_1/index.html
> +                <input type="checkbox" id="remember" name="remember" value="newsletter">
newsletter )

2020-11-23 07:46 UTC, merged