спроецировал пример
mishkalinda123/First pull request #8
Opened 2020-08-10 17:05 UTC by mishkalinda123

2020-08-11 19:17 UTC, SGolenzovskiy commented
Каким редактором ты пользуешься? Во всех современных редакторах должно быть автоформатирование (автоматические отступы). Попробуй применить его (отдельным коммитом). Код с корректными отступами и переносами упростит тебе его чтение.

2020-08-11 21:36 UTC, Golenzovskiy requested changes

2020-08-11 21:36 UTC, Golenzovskiy commented on project2.html
>  <h6 class="text-center">MAUREEN ZEHRING</h6>
Элементы, отображаемые в окне браузера, должны располагаться внутри body

2020-08-11 21:36 UTC, Golenzovskiy commented on project2.html
> +<div class="container-bg>
Потерянная кавычка ломает верстку

2020-08-11 21:36 UTC, Golenzovskiy commented on project2.html
> +<div><img src="img/img12.png.png></div>
Потерянная кавычка ломает верстку

2020-08-11 21:36 UTC, Golenzovskiy commented on project2.html
>      <div class="conteyner">
Опечатка?

2020-08-11 21:36 UTC, Golenzovskiy commented on project2.html
>  <div style="margin-top: 20px"></div>
Старайся избегать инлайн-стилей

2020-08-11 21:36 UTC, Golenzovskiy commented on project2.html
>          <H1 class="text-center">How to wrait headlines
Принято писать в нижнем регистре

2020-08-11 21:36 UTC, Golenzovskiy commented on project2.html
>          <tr><td class="text-center"></img><img src="img/img2.png.png"></td>
Закрывающий тег img не на месте

2020-08-13 19:43 UTC, mishkalinda123 commented on project2.html
> +<div class="container-bg>
понял.спасибо!подправлю..

2020-08-13 19:54 UTC, mishkalinda123 commented on project2.html
>      <div class="conteyner">
я так понял что я повторил <div class="conteyner">

2020-08-13 19:56 UTC, mishkalinda123 commented on project2.html
>      <div class="conteyner">
повторил div class conteyner

2020-08-13 20:13 UTC, mishkalinda123 commented on project2.html
>          <tr><td class="text-center"></img><img src="img/img2.png.png"></td>
я так понял что нужно убрать тег img за таблицу?
и подскажите нужно ли мне вообще таблицей пользоваться?

2020-08-13 20:27 UTC, mishkalinda123 commented on project2.html
>          <H1 class="text-center">How to wrait headlines
то есть h1?

2020-08-13 20:33 UTC, mishkalinda123 commented on project2.html
>  <div style="margin-top: 20px"></div>
я так понял что использование инлайн-стилей может повлиять на размер страницы

2020-08-13 20:58 UTC, SGolenzovskiy commented on project2.html
>          <H1 class="text-center">How to wrait headlines
Верно, рекомендуется использовать имена элементов нижнего регистра, так как:

- Смешивание прописных и строчных имен плохо
- Разработчики обычно используют строчные имена (как в XHTML)
- Нижний регистр выглядят чище
- Строчные легче писать

https://www.w3schools.com/html/html5_syntax.asp

2020-08-13 21:18 UTC, SGolenzovskiy commented on project2.html
>          <tr><td class="text-center"></img><img src="img/img2.png.png"></td>
Таблицы, как элементы верстки, уже (очень) давно не используются. Ранее таблицы использовали потому, что без них реализовать требуемую версту было практически невозможно. Сейчас теги таблиц (`table`, `tr`, `td `и т.п.) используются именно для представления таблиц как таковых (показать прайс на сайте, характеристики товара и т.п.). В настоящее (уже довольно длительное) время вместо "таблиц (`table`)" используются "блоки (`div`)" http://htmlbook.ru/html/div.

> я так понял что нужно убрать тег img за таблицу?

Не совсем это я имел ввиду. Сейчас проблема с тегом `</img>` в этой строке в том, что он явно не на своем месте. Если это закрывающий тег для тега `<img src="img/img2.png.png">`, то он явно не должен стоять перед ним. Если это закрывающий тег для другой картинки, то где его пара, что он "закрывает"? Скорее всего дело в том, что открывающий тег сильно выше по коду, а его закрывающий тег попал сюда (на эту строку) случайно.
Попробуй сделать авто-выравнивание в своем редакторе, обрати внимание на подсветку синтаксиса. Редактор должен как-то дать тебе понять, что верстка развалилась. Так (красные волнистые линии) выглядит выделение ошибки в моем редакторе

![image](https://user-images.githubusercontent.com/18659104/90188155-a1bb7680-ddc3-11ea-9b5d-b56b8ecea148.png)

2020-08-13 21:28 UTC, SGolenzovskiy commented on project2.html
>      <div class="conteyner">
Есть общепрнятое слово container - блок. Пример подразумевает, что ты улавливаешь его суть, а не просто копируешь строки. Практически наверняка можно быть уверенным в том, что в примере сделана опечатка и имелся ввиду container. В данном случае суть примера заключается в том, что ты прнимаешь блок (div), как некоторый контейнер. В качестве реализации выбранному блоку дается имя=класс. Т.е. ты пишешь:
1.  в шаблоне <div class="container"> (в нашем случае шаблон это html файл)
2. описываешь "стили" в таблице стилей, т.е. css

2020-08-13 21:37 UTC, SGolenzovskiy commented on project2.html
>  <div style="margin-top: 20px"></div>
Использование инлайн-стилей может быть оправдано в некоторых случаях:
1. нужно "перекрыть" (переопределить) стили из css
2. нужно внести правку "по быстрому", не тратя время на поиск нужно строки в css стилях

Оба варианта плохие и редкие, их нужно избегать! В этой строке ты делаешь отступ сверху, т.е. "верстаешь" страницу. Стили верстки (в т.ч. отступы) должны располагаться в файлах стилей (прим. css). Т.е. корректной правкой будет:
1. Добавление класса к этому блоку
2. Добавление отступа добавленному классу в css

> использование инлайн-стилей может повлиять на размер страницы

Это я не понял, к чему? :)

2020-08-13 21:42 UTC, Golenzovskiy requested changes
Ты увидел мой комментарий в начале прошлого ревью? Сделай, пожалуйста, авто-выравнивание тегов отдельным коммитом.

Постарайся максимально приблизиться к тому, что мы видим на исходной картинке:

![image](https://user-images.githubusercontent.com/18659104/90190563-e9dc9800-ddc7-11ea-9229-43f82b20eae2.png)

---

Сейчас результат сильно отличается от целевого. По крайней мере у меня страница отображается так:

![image](https://user-images.githubusercontent.com/18659104/90190692-27d9bc00-ddc8-11ea-8006-d32642b4e58b.png)

2020-08-15 16:17 UTC, sintsov commented on project2.html
>  <div style="margin-top: 20px"></div>
@mishkalinda123 все верно, еще один негативный эффект от использования инлайн-стилей -- это увеличение размера html-страницы.

2020-08-16 18:21 UTC, mishkalinda123 commented on project2.html
>          <H1 class="text-center">How to wrait headlines
с этим понял!

2020-08-18 20:00 UTC, SGolenzovskiy requested changes
Результат уже гораздо ближе к оригиналу, но еще есть заметные проблемы на десктопных мониторах (1920px). Обрати внимание, насколько разные отступы слева и справа и какой разрыв между текстом и картинкой по центру.
![image](https://user-images.githubusercontent.com/18659104/90559559-67c4e880-e1a6-11ea-9418-a6c1078251fb.png)

2020-08-18 20:00 UTC, Golenzovskiy commented on project2.html
> +                    <img class="im" src="img/img1.png.png">
> png.png

С названиями файлов что-то пошло не так )

2020-08-18 20:00 UTC, Golenzovskiy commented on project2.html
> +        <table cellpadding="5" cellspacing="0">
Использование таблицы здесь не вполне уместно. Такие компоненты-блоки лучше всего верстать внутри div-блоков. Таблицы уместны там, где они должны быть "семантически". В остальных случаях (ради вёрстки html) нужно использовать `div`. 

На примере https://www.mvideo.ru/:

Таблица используется для представления характеристик товара:
https://www.mvideo.ru/products/smartfon-oppo-a52-4-64gb-stream-white-cph2069-30049721?from=obzor
![image](https://user-images.githubusercontent.com/18659104/90558218-5e3a8100-e1a4-11ea-932e-d4b91c248f99.png)

Блоки (div) используются как средство верстки:
https://www.mvideo.ru/ (блок новостей над футером)
![image](https://user-images.githubusercontent.com/18659104/90558620-0c462b00-e1a5-11ea-85f4-c06212acbc08.png)

2020-08-19 19:41 UTC, mishkalinda123 commented on project2.html
> +                    <img class="im" src="img/img1.png.png">
согласен)))болбес)поправлю!)

2020-08-19 19:46 UTC, mishkalinda123 commented on project2.html
> +        <table cellpadding="5" cellspacing="0">
хорошо!буду доводить до ума..
у меня на мониторе все ровненько!прада разрешение максимальное 1280*1024))

2020-08-19 21:14 UTC, SGolenzovskiy commented on project2.html
> +        <table cellpadding="5" cellspacing="0">
Сейчас главное не скорость выполнения, а результат. Лучше сейчас потрать больше времени на доработку, перед отправкой на ревью проверь страницу на разных разрешениях экрана, в разных браузерах.

Чем меньше итераций совершит pull request (появляются замечания, ты дорабатываешь), тем быстрее получиться разобраться с этой задачей и двинуться дальше.

2020-10-19 21:04 UTC, mishkalinda123 commented on project2.html
> +                    <img class="im" src="img/img1.png.png">
Задал разрешение и подправил отступы..

2020-10-27 20:38 UTC, SGolenzovskiy requested changes
На самом деле это хороший результат. Есть недочеты по адаптивности, но таких требований в задаче и не фиксировалось, поэтому давай исправим последний момент - сайт должен адекватно отображаться в актуальных браузерах. В целом везде все нормально, но нужно подправить верстку в браузере Microsoft Edge (бывш. Explorer) и сможем двигаться дальше, к новым задачам.

---
Microsoft Edge (1920x1080 px):
![image](https://user-images.githubusercontent.com/18659104/97358976-1ffcc480-18ad-11eb-9642-0ad7a2159198.png)

2020-10-27 20:38 UTC, SGolenzovskiy commented on css/style.css
> +    display: -moz-inline-stack;
`-moz-inline-stack` объявлен depricated, т.е. не должен использоваться, зачем он тебе? Какую проблему он решал?

https://developer.mozilla.org/en-US/docs/Web/CSS/display

2020-10-27 20:38 UTC, SGolenzovskiy commented on css/style.css
> +    display: -moz-inline-stack;
`-moz-inline-stack` depricated (см. мой коммент выше)

2020-10-27 21:15 UTC, mishkalinda123 commented on css/style.css
> +    display: -moz-inline-stack;
Я думал он подправит смещение картинки и текста...
на каком-то форуме вычитал
после уже подправил а убирать не стал.

мне к стати кажется что я много где лишнего и не нужного добавил..

2020-11-16 18:50 UTC, merged